/**
 * ゲームの定数定義（後方互換性のためのエイリアス）
 *
 * このファイルは新しいData層への移行期間中の互換性のために存在します。
 * 新しいコードはData層から直接インポートしてください。
 */

export {
  GRID_SIZE,
  BASE_CELL_SIZE,
  SLOT_COUNT,
  COLORS,
  ANIMATION,
  LAYOUT,
  CELL_STYLE,
  CLEAR_ANIMATION,
  SCORE_STYLE,
  DECK_CONFIG,
  HANDS_STYLE,
  ROUND_CONFIG,
  GOLD_STYLE,
  ROUND_STYLE,
  ROUND_CLEAR_STYLE,
  GAME_OVER_STYLE,
  GAME_CLEAR_STYLE,
  SHOP_STYLE,
  DEBUG_WINDOW_STYLE,
  PATTERN_COLORS,
  PATTERN_SYMBOL_STYLE,
  SEAL_COLORS,
  SEAL_SYMBOL_STYLE,
  DEBUG_PROBABILITY_SETTINGS,
} from './Data/Constants'
